worker_processes  auto;
events {
  worker_connections  1024;
}
http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  client_max_body_size 0;

  server {
    listen 80;
    server_name _;

    autoindex off;

    location = /healthz {
      access_log off;
      return 200 "ok\n";
    }

    location /data/ {
      alias /data/;
      dav_methods PUT DELETE MKCOL COPY MOVE;
      create_full_put_path on;
      dav_access group:rw all:r;
    }
  }
}
